<!DOCTYPE HTML>
             <html>
                 <head>
                     <title>Sign in to Intacct</title>
                     <meta http-equiv="content-type" content="text/html; charset=UTF-8">
                     <!-- Keep the caching so the browser remember ID / password -->
                     <!-- <meta http-equiv="Pragma" content="no-cache"> -->

                     <link rel="stylesheet" type="text/css" href="../resources/css/login_style.css">
                     <script src="../resources/thirdparty/jquery/jquery-1.11.3.min.js" language="javascript"></script><script src="../resources/thirdparty/jquery/jquery-migrate-1.2.1.min.js" language="javascript"></script>
<script language="javascript">
jq=jQuery.noConflict();
</script>

                     <script type="text/javascript" src="../resources/js/base_lib.js"></script>
                     <script type="text/javascript" src="../resources/js/login.js"></script>

                     <script>

                         <!-- Set up screen width and height cookie for the old menu -->
                         setScreenSizeCookies(); 

                         <!-- Begin UA Tracking Code added by E-Nor-->
                         (function(i,s,o,g,r,a,m){i["GoogleAnalyticsObject"]=r;i[r]=i[r]||function(){
                         (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                         m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
                         })(window,document,"script","//www.google-analytics.com/analytics.js","ga");

                         var mainDomainParts = document.location.hostname.match(/(([^.\/]+\.[^.\/]{2,3}\.[^.\/]{2})|(([^.\/]+\.)[^.\/]{2,4}))(\/.*)?$/);
                         var mainDomain = mainDomainParts ? mainDomainParts[1] : "intacct.com";
                         mainDomain = mainDomain.toLowerCase();

                         ga("create", "UA-174496-1", mainDomain, {"allowLinker": true} );
                         ga("send", "pageview");
                         <!-- End UA Tracking Code -->

                        jq(window).bind("message", function(e) {
                            var re = /height: ([0-9]+)/;
                            var matches = re.exec(e.originalEvent.data);
                            if (matches) {
                                var $container = jq("#marketingcontent").parent();
                                $container.height(matches[1]);
                                $container.css("overflow", "hidden");
                            }
                        });

                     </script>

                 </head>
                 <body class="" onload="onLoadLogin();">
                    <div class="full_login">
                        <div class="header">
                            <div class="links">
                                <a href="http://us.intacct.com">Home</a>
                                <span>|</span>
                                <a href="http://us.intacct.com/secure-accounting-software">Security</a>
                                <span>|</span>
                                <a href=" http://us.intacct.com/system-status">System Status</a>
                            </div>
                            <div class="logos">
                                <div class="float_left">
                                    <a href="http://us.intacct.com">
                                        <img src="../resources/images/ia-app/logos/intacct_logo_banner.png" />
                                    </a>
                                </div>
                                <div class="float_right">
                                    <a href="http://us.intacct.com/aicpa-preferred-financial-management-solution">
                                        <img src="../resources/images/ia-app/logos/logo-aicpa.gif" />
                                    </a>
                                </div>
                            </div>
                            <div>
                                <img src="../resources/images/ia-app/login/signin_banner_960.png" />
                            </div>  
                        </div>
                        <div class="login_content"><div class="marketing_banner">
                            <iframe id="productcontent" scrolling="no" frameborder="0" src="https://www.intacct.com/ia/logincontent/product/index.html">
                            </iframe></div><div class="loginbox">
                                <div class="loginbox_header">
                                    <div class="loginbox_header_wrapper">
                                        <span id="loginbox_text_signin" class="loginbox_text">Sign in</span>
                                        <a id="GoToSSOLink" class="loginbox_text" style="float:right;visibility:visible;display:block" href="#" onclick="toggleSSO(true); return false;">Use single sign-on</a>
                                        <a id="GoToLoginLink" class="loginbox_text" style="float:right;visibility:hidden;display:none" href="#" onclick="toggleSSO(false); return false;">Use basic sign-in</a>
                                     </div>
                                </div>
                                <form name="iamain" method="post" action="login.phtml?.done=frameset.phtml" onsubmit="encryptParam('.passwd');">
                                    <input type="hidden" name=".uesp" value="">
                                    <input type="hidden" name=".issso" id="issso" value="0">
                                    <input type="hidden" id="metrofield" name=".metro" value="0">
                                    <input type="hidden" id="ssotesterror" name=".ssotesterror" value="">
                                    <input type="hidden" name=".login_id" value="._!AReafPGrC28DEEqgBVwDCFBE">
                                    <input type='hidden' name='.xsrf_token' value='NDk2Yjc5MWQ5NjY3ZjhhMzc3OWYyYzM4NTYwMzkwMmYyYjM5YjM1MDllMTExYWQxNGM1ZjZiMjZkZDlmODdkNg..'>
                                    <ul>
                                        <li class="login_error"></li>
                                        <li>
                                            <label for="company">Company ID</label>
                                            <input type="text" name=".company" id="company" value="" 
                                             maxlength="40" onchange="clear_error(this.id)" tabindex="1"/>
                                            <img src="../resources/images/ia-app/icons/error.png" id="company_error" 
                                                class="error"
                                            />
                                        </li><li> 
                <label for="login">User ID</label>
                <input type="text" name=".login" id="login" value="" 
                        maxlength="20" onchange="clear_error(this.id)" tabindex="2"
                />
                <img src="../resources/images/ia-app/icons/error.png" id="login_error" class="error" />
            </li><li id="passwordBlock" style="visibility:visible;display:block">
                <label for="passwd">Password</label>
                <input type="password" name=".passwd" id="passwd" autocomplete="off" 
                        onchange="clear_error(this.id)"  tabindex="3"
                />
                <img src="../resources/images/ia-app/icons/error.png" id="passwd_error" class="error" />
              </li>
              <li>
                
                                    <li id="passwordForgot" style="visibility:visible;display:block" class="right_align"> 
                                        <a tabindex="6"
                                         href="resetpassword.phtml?.done=frameset.phtml">Forgot your password?</a>
                                    </li>
                                    <li>
                                        <label>&nbsp;</label>
                                        <input type="submit" name=".ret" id="retbutton" value="Sign in" 
                                            onclick="return login_validation();" tabindex="4"/>
                                    </li>
                                    <li id="remembermeBlock">
                                        <label>&nbsp;</label>
                                        <input type="checkbox" name=".rememberme" tabindex="5"
                                         id="rememberme" >
                                        <span>Remember me</span>
                                    </li></ul>
                            </form>
                        </div>
                        <div>
                            <div class="marketingcontentholder">
                               <iframe id="marketingcontent" scrolling="no" frameborder="0" src="https://www.intacct.com/ia/logincontent/marketing/index.html">
                                </iframe>
                            </div>
                            <div class="page_footer">
                                <div class="link">
                                    <a href="http://us.intacct.com/status" target="_blank">Uptime</a>
                                    <span>|</span>
                                    <a href="http://www.intacct.com/company_privacy.html" target="_blank">
                                        Privacy Policy
                                    </a>
                                    <span>|</span>
                                    <a href="http://us.intacct.com" target="_blank">
                                        &copy; 1999 - <script>document.write(new Date().getFullYear());</script> 
                                        Intacct Corporation
                                    </a>
                                </div>
                            </div>
                        </div> 
                    </div>
                </div><iframe src='https://www.intacct.com/ia/acct/login.phtml?.topper=1' marginwidth='0' marginheight='0' frameborder='0' vspace='0' hspace='0' style='height: 1px; width: 1px;'></iframe>
            </body>
        </html>